### ISSUE TITLE
Latest build not working with fresh install

### ISSUE THREAD

**Issue by danlourenco** [CANVE/canve-viz#35]
Hi All, I cloned this project and was unable to run this repo.  Looks like there was a failure to fetch localhost:31338/canve-data/nodes.  Should I be serving up some sort of backend here locally?

**Comment by matanox** [comment]
Hi Dan, as much as we're flattered, at this point in time this repo is actually a WIP refactoring an early proof-of-concept GUI. There's a simple way for serving the backend data locally for this repo here, and there's also a separate repo housing the initial GUI proof-of-concept, which may even give you a better overall impression of where this is heading. Please let us know which one's interesting right now... but if you were looking for something ready to use you're too early around..

**Comment by danielabar** [comment]
Sorry the readme is not up to date with the part about serving the data, in part because we haven't yet decided where the data will ultimately come from. For now, the data comes from [this project](https://github.com/CANVE/visualizer). After you check it out, run:

```
python serveLocalCORS.py
```

That serves up the nodes and edges data required by canve-viz.

**Comment by danielabar** [comment]
@dlo83 I updated the [readme](https://github.com/CANVE/canve-viz/blob/master/README.md) with step to also run the local server. Let me know if its working for you?
